### ISSUE TITLE
(Possibly) Incorrecty self-registered MT_MODE causes degraded performance with Prefetch(>1)

### ISSUE THREAD

**Issue by Kogarou-san** [Asd-g/AviSynthPlus-NNEDI3CL#3] opened 2022-08-06 15:46 UTC
_Note: I've played around and made my own rather simple AVS+ plugins before, but I not an expert when it comes to software development, GPGPU and parallelization._

I've ran across this issue yesterday at night when attempting to run [Dogway's QTGMC+](https://github.com/Dogway/Avisynth-Scripts/blob/75ac682b5559a426d43d1ca7abda8574ffa0f341/MIX%20mods/QTGMC%2B.avsi) and enabling nnedi3cl in it, and managed to pin down the issue with it: running nnedi3cl() and enabling Prefetch() with any number other than 1 increases (at least) the cost in CPU usage when running nnedi3cl. I assume the amount increases somewhat linearly the more threads Prefetch() sets for the plugins.
Just to be sure, I checked the code and [the plugin self registers its MT_MODE as MT_MULTI_INSTANCE](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/blob/main/src/NNEDI3CL.cpp#L230):
```cpp
int AVSC_CC NNEDI3CL_set_cache_hints(AVS_FilterInfo* fi, int cachehints, int frame_range)
{
    return cachehints == AVS_CACHE_GET_MTMODE ? 2 : 0;
}
```
Forcing the plugin to run with MT_SERIALIZED via
```cpp
SetFilterMTMode("NNEDI3CL_NNEDI3CL", MT_SERIALIZED, true)
```
restores the performance I expected out of the plugin at a much saner CPU usage for itself.
From what I an idea of, using MT_SERIALIZED is the best choice when working with code running on the GPU, and it's exactly what FFT3DGPU uses. _**However**_ KNLMeansCL also sets his hown MT_MODE as MT_MULTI_INSTANCE, and it also suffers the exact same issue on my system. Is MT_MULTI_INSTANCE beneficial when using a GPU faster than a GTX 1050Ti? Or is this a mishap that got copied from other plugins using OpenCL, rinse and repeat? At the time of this post, I haven't been able to confirm with anyone else if they can replicate the same behaviour. All I need to do is a simple
```cpp
ColorBarsHD()
SetFilterMTMode("NNEDI3CL", MT_SERIALIZED, true) #comment to remove the forced MT_MODE
nnedi3cl(3, nns=4, pscrn=2, list_device=false, info=false, device=0) #changing quality/speed values likely won't do anything
Prefetch(12,12)
```
[Video here](https://kogarou.s-ul.eu/Xse3f3s8.mp4)
Am I just dumb and having a lapse of intelligence? Or did I found a recurring issue affecting a few OpenCL AVS+ plugins?
The idea i got from the few people I've talked to is that some, even in AVS+, didn't/don't use Prefetch() to save CPU resources for the encoding software running along. And who knows how many have been wasting CPU cycles in KNLMeansCL for years and have never noticed? At least with NNEDI3 we now have a CPU and GPU version, and what made me find this was checking how fast each one compared to the other on a de-interlacing script.
Using `NNEDI3CL 1.0.2` and `AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)` (compiled by myself in VS2022 a few weeks ago)
Can you replicate this on your system?

**Comment by Asd-g** [comment] 2022-08-06 16:39
I cannot reproduce it.
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                   215784
Length (hh:mm:ss.ms):         00:59:59.996
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                   172799827

Frame (current | last):             542 | 215783
FPS (cur | min | max | avg):        3.660 | 3.534 | 138892 | 42.98
Process memory usage:               262 MiB
Thread count:                       39
CPU usage (current | average):      1.0% | 0.9%

Time (elapsed | estimated):         00:00:12.611 | 01:23:40.760

[Script]
ColorBarsHD()
SetFilterMTMode("NNEDI3CL", MT_SERIALIZED, true) #comment to remove the forced MT_MODE
nnedi3cl(3, nns=4, pscrn=2, list_device=false, info=false, device=0) #changing quality/speed values likely won't do anything
Prefetch(12,12)
```

```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                   215784
Length (hh:mm:ss.ms):         00:59:59.996
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                   172799827

Frame (current | last):             780 | 215783
FPS (cur | min | max | avg):        110.1 | 63.05 | 128.0 | 91.50
Process memory usage:               354 MiB
Thread count:                       50
CPU usage (current | average):      1.5% | 2.5%

Time (elapsed | estimated):         00:00:08.525 | 00:39:18.408

[Script]
ColorBarsHD()
#SetFilterMTMode("NNEDI3CL", MT_SERIALIZED, true) #comment to remove the forced MT_MODE
nnedi3cl(3, nns=4, pscrn=2, list_device=false, info=false, device=0) #changing quality/speed values likely won't do anything
Prefetch(12,12)
```

It depends on CPU/GPU/RAM (speed, timings), if the filter is used alone or with other filters, what are the other filters.
When this is used as a part of huge script as QTGMC, it's hard/nearly impossible to do fine tuning but when it's used as separated filter prefetch can be used for every filter in the script for fine tuning.

**Comment by Kogarou-san** [comment] 2022-08-06 16:55
> It depends on CPU/GPU/RAM

It definitely does, and I forgot to specificy my hardware.
`Ryzen 5 5600`
`GTX 1050 Ti` over PCIe 3
`DDR4 16GB 3733MHz` in dual-channel
Also my bad, forgot to note that you should change the Prefetch() values to fit with your CPU. Mine has 6 cores with SMT, so 12 is a fair number (the defaults would choose 13 actually but its more than enough to trigger this)
What are your specs?

**Comment by Asd-g** [comment] 2022-08-06 17:45
i9 7900x (x86@4800, AVX2@4400, AVX512@3700)
RX480 8GB PCie@x16 (3.0)
4x8GB@4000-17-19-19-39 (quad channel)

Usually the prefetch number should be something like cpu_cores(cores not threads)/2. Usually for light filters it should be lower and for heavy filters it can be higher. Also depends what is the fps of the filter input - generally something like this can be used as base: prefetch_number=input_fps/output_fps(without prefetch).

Also sometimes caching a lot of frames can be beneficial to prefetch:
```
source filter
RequestLinear(100) # cache 100 frames
filters
```
[RequestLinear](https://github.com/pinterf/TIVTC/blob/master/Doc_TIVTC/RequestLinear%20-%20READ%20ME.txt) can be beneficial for temporal filters too. Btw KNLMeansCl is temporal filter while nnedi3 is spatial. You can test with RequestLinear before KNLMeansCl.

**Comment by DonCanjas** [comment] 2022-08-06 21:14
I happen to have the same problem with both NNEDI3CL and KNLMeansCL.

`i7-9750H`
`GTX 1650` (some software reports it as max-q, not really sure which but it's a laptop)
`2x8GB 2666MHz`

```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                     2161
Length (hh:mm:ss.ms):         00:01:12.105
Frame width:                          1288
Frame height:                          720
Framerate:                          29.970 (30000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     3461057

Frames processed:                   2161 (0 - 2160)
FPS (min | max | average):          32.62 | 226757 | 64.20
Process memory usage (max):         253 MiB
Thread count:                       34
CPU usage (average):                8.3%

Time (elapsed):                     00:00:33.659


[Script]

ColorBarsHD().Trim(0, 2160)

SetFilterMTMode("NNEDI3CL_NNEDI3CL", 3, true)
NNEDI3CL(1, nsize=3, nns=3, qual=1, pscrn=2)

Prefetch(6)
```


```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                     2161
Length (hh:mm:ss.ms):         00:01:12.105
Frame width:                          1288
Frame height:                          720
Framerate:                          29.970 (30000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     3461057

Frames processed:                   2161 (0 - 2160)
FPS (min | max | average):          29.92 | 93.72 | 53.22
Process memory usage (max):         696 MiB
Thread count:                       64
CPU usage (average):                49.4%

Time (elapsed):                     00:00:40.607 


[Script]

ColorBarsHD().Trim(0, 2160)

#SetFilterMTMode("NNEDI3CL_NNEDI3CL", 3, true)
NNEDI3CL(1, nsize=3, nns=3, qual=1, pscrn=2)

Prefetch(6)
```

**Comment by Asd-g** [comment] 2022-08-06 22:05
@Kogarou-san, @DonCanjas can you test with Prefetch(2)?

**Comment by Kogarou-san** [comment] 2022-08-06 22:39
```cpp
ColorBarsHD()
nnedi3cl(3, nns=4, pscrn=2, list_device=false, info=false, device=0)
Trim(0,4999)
Prefetch(X)
```
1:
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     5000
Length (hh:mm:ss.ms):         00:01:23.417
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     4004000

Frames processed:                   5000 (0 - 4999)
FPS (min | max | average):          42.11 | 56.18 | 54.99
Process memory usage (max):         334 MiB
Thread count:                       24
CPU usage (average):                8.2%

GPU usage (average):                96%
VPU usage (average):                0%
GPU memory usage:                   618 MiB
GPU Power Consumption (average):    78.2 W

Time (elapsed):                     00:01:30.925
```

2:
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     5000
Length (hh:mm:ss.ms):         00:01:23.417
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     4004000

Frames processed:                   5000 (0 - 4999)
FPS (min | max | average):          11.65 | 166667 | 49.32
Process memory usage (max):         417 MiB
Thread count:                       32
CPU usage (average):                16.0%

GPU usage (average):                98%
VPU usage (average):                0%
GPU memory usage:                   665 MiB
GPU Power Consumption (average):    76.4 W

Time (elapsed):                     00:01:41.373
```
I've tested it up to Prefetch(6) and it ever got over 49.72 FPS at the end of the script. Took the opportunity to have AVSMeter read GPU stats via GPU-Z. The GPU clocks stay fixed at 1949MHz in all tests. The 5FPS difference between the result with Prefetch(1) and all others is consistent

**Comment by DonCanjas** [comment] 2022-08-07 13:29
> can you test with Prefetch(2)?

```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                     2161
Length (hh:mm:ss.ms):         00:01:12.105
Frame width:                          1288
Frame height:                          720
Framerate:                          29.970 (30000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     3461057

Frames processed:                   2161 (0 - 2160)
FPS (min | max | average):          47.24 | 56.61 | 53.39
Process memory usage (max):         297 MiB
Thread count:                       36
CPU usage (average):                16.6%

Time (elapsed):                     00:00:40.473


[Script]

ColorBarsHD().Trim(0, 2160)

#SetFilterMTMode("NNEDI3CL_NNEDI3CL", 3, true)
NNEDI3CL(1, nsize=3, nns=3, qual=1, pscrn=2)

Prefetch(2)
```

```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                     2161
Length (hh:mm:ss.ms):         00:01:12.105
Frame width:                          1288
Frame height:                          720
Framerate:                          29.970 (30000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     3461057

Frames processed:                   2161 (0 - 2160)
FPS (min | max | average):          45.47 | 93.75 | 64.60
Process memory usage (max):         209 MiB
Thread count:                       30
CPU usage (average):                8.3%

Time (elapsed):                     00:00:33.453


[Script]

ColorBarsHD().Trim(0, 2160)

SetFilterMTMode("NNEDI3CL_NNEDI3CL", 3, true)
NNEDI3CL(1, nsize=3, nns=3, qual=1, pscrn=2)

Prefetch(2)
```

**Comment by Asd-g** [comment] 2022-08-07 18:39
Thanks for the tests.

@DonCanjas, what avs+ build are you using?

Test the attached version. It has additional parameter `st` (default false). When it's true it's similar to as if the filter is MT_SERIALIZED but with the benefit to not register the filter as MT_SERIALIZED.

If you do `SetFilterMTMode("NNEDI3CL_NNEDI3CL", MT_SERIALIZED, true)`, it means every filter before NNEDI3CL in the chain will be in MT_SERIALIZED mode. For example:
```
SetFilterMTMode("NNEDI3CL", MT_SERIALIZED, true)
source_filter
filter1
filter2
filter3
NNEDI3CL
```
In the above example - filter1, filter2, filter3 will be forced in MT_SERIALIZED mode too.

[NNEDI3CL-1.0.2a.zip](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/files/9277288/NNEDI3CL-1.0.2a.zip)

**Comment by DonCanjas** [comment] 2022-08-07 21:43
> @DonCanjas, what avs+ build are you using?
> 
Atm, in order to use avslibplacebo, I'm using r3682 build from: https://gitlab.com/uvz/AviSynthPlus-Builds

```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                     2161
Length (hh:mm:ss.ms):         00:01:12.105
Frame width:                          1288
Frame height:                          720
Framerate:                          29.970 (30000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     3461057

Frames processed:                   2161 (0 - 2160)
FPS (min | max | average):          41.00 | 83.72 | 53.02
Process memory usage (max):         695 MiB
Thread count:                       64
CPU usage (average):                49.4%

Time (elapsed):                     00:00:40.761
PS C:\Users\jonas\Desktop\avsi\Misc> avsmeter64 memez.avs


[Script]

ColorBarsHD().Trim(0, 2160)

NNEDI3CL(1, nsize=3, nns=3, qual=1, pscrn=2)

Prefetch(6)

```

```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3682, 3.7, x86_64) (3.7.2.0)

Number of frames:                     2161
Length (hh:mm:ss.ms):         00:01:12.105
Frame width:                          1288
Frame height:                          720
Framerate:                          29.970 (30000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     3461057

Frames processed:                   2161 (0 - 2160)
FPS (min | max | average):          39.60 | 174216 | 63.14
Process memory usage (max):         696 MiB
Thread count:                       64
CPU usage (average):                8.3%

Time (elapsed):                     00:00:34.225


[Script]

ColorBarsHD().Trim(0, 2160)

NNEDI3CL(1, nsize=3, nns=3, qual=1, pscrn=2, st=true)

Prefetch(6)
```
> If you do SetFilterMTMode("NNEDI3CL_NNEDI3CL", MT_SERIALIZED, true), it means every filter before NNEDI3CL in the chain will 

Isn't there a way to force only one filter to use the specified MT Mode?

**Comment by Kogarou-san** [comment] 2022-08-07 23:00
> If you do `SetFilterMTMode("NNEDI3CL_NNEDI3CL", MT_SERIALIZED, true)`, it means every filter before NNEDI3CL in the chain will be in MT_SERIALIZED mode. 

Are you serious? I haven't read anything like that on the wiki before. Is it due to forcing the mode? If not, what about other filters before that also self-register their `MT_MODE`?

I've tested and the switch gives me as much FPS and CPU usage as forcing MT_SERIALIZED, so it's definitely doing something. The used RAM and VRAM increases with more threads set in prefetch, which doesn't happen when forcing the MT_MODE.

**Comment by Kogarou-san** [comment] 2022-08-08 04:32
With this test build I decided to benchmark nnedi3cl when used in a big but real script (QTGMC+), since I could edit one of the script's dependencies to enable/disable `st` at every nnedi3cl call:

1. `st=true` and running the script without forced `MT_SERIALIZED`; 
2. `st=false` and running the script with forced `MT_SERIALIZED` inserted in MtModes.avsi;
3. `st=false` and running the script without forced `MT_SERIALIZED`; 
[1] represents your changes, [2] represents what I had in mind, [3] represents old behaviour

This is the script's contents
```cpp
SetMemoryMax(12000)
LWLibavVideoSource("<standard NTSC DVD>", threads=1, decoder="mpeg2_cuvid")

QTGMCp(Preset="Slower", NNSize=0, NNeurons=4, EdiQual=2, TrueMotion=true, ChromaMotion=true, ThSAD1=500,
ThSAD2=200, Blocksize=4, ForceTR=6, SubPel=4, NoiseProcess=0, ChromaNoise=false, Denoiser="", NoiseTR=0, Sigma=0,
NoiseDeint="", StabilizeNoise=false, DenoiseMC=false, show=false, tv_range=true, device_type="GPU", device_id=0)
Prefetch(6)
Trim(0,999)
```
It is definitely not one that is GPU bound at all, atleast on my hardware, but there should still be differences in performance and resource usage. In skimming thru the code, nnedi3cl is called atleast 4 times per frame in this script. Tests were performed twice and the numbers did not diverge more than 1.5% between the same test .

[1]
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     1000
Length (hh:mm:ss.ms):         00:00:16.683
Frame width:                           720
Frame height:                          480
Framerate:                          59.940 (60000/1001)
Colorspace:                           i420

Frames processed:                   1000 (0 - 999)
FPS (min | max | average):          3.335 | 37175 | 8.974
Process memory usage (max):         2087 MiB
Thread count:                       66
CPU usage (average):                23.8%

GPU usage (average):                11%
VPU usage (average):                4%
GPU memory usage:                   917 MiB
GPU Power Consumption (average):    49.6 W

Time (elapsed):                     00:01:51.430
```

[2]
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     1000
Length (hh:mm:ss.ms):         00:00:16.683
Frame width:                           720
Frame height:                          480
Framerate:                          59.940 (60000/1001)
Colorspace:                           i420

Frames processed:                   1000 (0 - 999)
FPS (min | max | average):          3.557 | 36900 | 9.091
Process memory usage (max):         1965 MiB
Thread count:                       33
CPU usage (average):                24.1%

GPU usage (average):                11%
VPU usage (average):                5%
GPU memory usage:                   697 MiB
GPU Power Consumption (average):    49.7 W

Time (elapsed):                     00:01:50.005
```

[3]
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     1000
Length (hh:mm:ss.ms):         00:00:16.683
Frame width:                           720
Frame height:                          480
Framerate:                          59.940 (60000/1001)
Colorspace:                           i420

Frames processed:                   1000 (0 - 999)
FPS (min | max | average):          2.409 | 39841 | 8.641
Process memory usage (max):         2143 MiB
Thread count:                       67
CPU usage (average):                23.3%

GPU usage (average):                11%
VPU usage (average):                4%
GPU memory usage:                   918 MiB
GPU Power Consumption (average):    49.7 W

Time (elapsed):                     00:01:55.723
```
[1] runs 3.8% faster than [3] at the same VRAM usage and interestingly less RAM usage, unexpected for me; [2] runs 5.2% faster than [3] at less VRAM and RAM usage.
I cannot refute your statement of
> If you do SetFilterMTMode("NNEDI3CL_NNEDI3CL", MT_SERIALIZED, true), it means every filter before NNEDI3CL in the chain will be in MT_SERIALIZED mode.

but it doesn't seem to be happening to me at least. Maybe something changed in the meanwhile in AVS+ and it doesn't happen anymore, I don't know.
The benchmarks could have ran for much longer, I stopped them short because i don't want to fall asleep looking at numbers tick, it's 05:30 as I'm typing these words.
setting `st=true` does help compared to the old behaviour so there's that, but It doesn't achieve the same results resource-wise , and by extension, in performance compared to `MT_SERIALIZED`. More testing could and should be done to get a better picture

**Comment by Asd-g** [comment] 2022-08-08 12:04
> 
> Are you serious? I haven't read anything like that on the wiki before. Is it due to forcing the mode? If not, what about other filters before that also self-register their `MT_MODE`?
> 
> I've tested and the switch gives me as much FPS and CPU usage as forcing MT_SERIALIZED, so it's definitely doing something. The used RAM and VRAM increases with more threads set in prefetch, which doesn't happen when forcing the MT_MODE.

Test with:
```
SetFilterMTMode("vinverse", MT_SERIALIZED, true) # comment/remove comment
ColorBarsHD().KillAudio()
vstbilateral()
vinverse()
prefetch(2)
```
In the above example the bottleneck is `vstbilateral()` so `vinverse()` with or without prefetch wouldn't effect the speed. With commented first line the speed shows that `vstbilateral()` is running with `prefetch(2)`. With removed comment from the first line the speed shows that `vstbilateral()`is running in MT_SERIALIZED mode too.

>
> Isn't there a way to force only one filter to use the specified MT Mode?

The workaround of the behavior from the above test is:
```
SetFilterMTMode("vinverse", MT_SERIALIZED, true) # comment/remove comment
ColorBarsHD().KillAudio()
vstbilateral()
prefetch(2)
vinverse()
prefetch(2)
```
But when you have gigantic script (QTGMC) with multiple filters the above workaround isn't possible. 

Btw this is already discussed for KNLMeansCL - [check this post](https://forum.doom9.org/showthread.php?p=1823754#post1823754) that is reply for [this script](https://forum.doom9.org/showthread.php?p=1823726#post1823726).

**Comment by Kogarou-san** [comment] 2022-08-09 21:06
So in essence, this is a problem with AVS+? Well this is though, guess the only thing it can be done is to fill an issue in its repo to fix this.

**Comment by Asd-g** [comment] 2022-08-11 16:59
@Kogarou-san, @DonCanjas can you test the attached versions with (don't try `st=false`, they will crash probably):
```
ColorBarsHD()
nnedi3cl(3, nns=4, pscrn=2, st=true)
Trim(0,4999)
Prefetch(6)
```
[NNEDI3CL_test.zip](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/files/9310070/NNEDI3CL_test.zip)


> Are you serious? I haven't read anything like that on the wiki before. Is it due to forcing the mode? If not, what about other filters before that also self-register their MT_MODE?

It's not only when mt mode is forced by user (`SetFilterMTMode("xxx", N, true)`).

1 : MT_NICE_FILTER
2 : MT_MULTI_INSTANCE
3 : MT_SERIALIZED

These are the 99.9% of the used mt modes.

When you have X filter with mt mode N you also make every filter before this filter X to change it's mode if it's lower than the X mode. For example:
```
SetFilterMTMode("filter3", 3, true)
source
filter1 # it has mt mode 3
filter2 # it has mt mode 1
filter3 # forcing mt mode 3
prefetch(2)
```

In the above example `filter2` has lower mt mode (1) than the forced one so it will be changed to 3 (MT_SERIALIZED).

Another example:
```
source
filter1 # it has mt mode 3
filter2 # it has mt mode 3
filter3 # it has mt mode 2
prefetch(2)
```

In the above example both `filter1` and `filter2` have higher mt mode (3) than `filter3` so they will be not changed.

Another example (with real filters so you can test):
```
ColorBarsHD().KillAudio()
vstbilateral() # mt mode 2
hqdn3d() # mt mode 3
# prefetch(2) # if you use prefetch() after filter with mt mode 3 you will have even worse fps compared to the case if you don't use prefetch()
```

In the above example the bottleneck is `vstbilateral()` and it has lower mt mode than `hqdn3d()` so it will be changed to 3 too.

You can compare the previous example with this variant:
```
ColorBarsHD().KillAudio()
vstbilateral() # mt mode 2
prefetch(2)
hqdn3d() # mt mode 3
```

> So in essence, this is a problem with AVS+? Well this is though, guess the only thing it can be done is to fill an issue in its repo to fix this.

In essence this is a part of the AVS+ mt design. If you cant put prefetch after every filter you will have the behavior described above. But feel free to open issue in the AVS+ repo.

**Comment by Kogarou-san** [comment] 2022-08-14 16:15
NNEDI3CL_write.dll with `st=true` returns the clip correctly, with `st=false` it transforms into a arguably really cool "Corrupted Video VFX". There's always a silver lining somewhere 👍 ;
NNEDI3CL_read.dll with `st=true` returns the clip correctly, returns corrupted planes with `st=false` somewhat similarly to NNEDI3CL_write.dll , they are not as corrupted;
NNEDI3CL_enq.dll with `st=true` returns the clip correctly, returns returns corrupted planes with `st=false` almost, if not exactly, in the same way as with NNEDI3CL_read.dll;

Since all 3 were returning incorrect clips with `st=false`, the only worthwhile tests I can do involve `st=true`
NNEDI3CL_write.dll:
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     5000
Length (hh:mm:ss.ms):         00:01:23.417
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     4004000

Frames processed:                   5000 (0 - 4999)
FPS (min | max | average):          4.624 | 192308 | 49.63
Process memory usage (max):         725 MiB
Thread count:                       64
CPU usage (average):                49.2%

GPU usage (average):                99%
VPU usage (average):                0%
GPU memory usage:                   1168 MiB
GPU Power Consumption (average):    77.2 W

Time (elapsed):                     00:01:40.752
```

NNEDI3CL_read.dll:
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     5000
Length (hh:mm:ss.ms):         00:01:23.417
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     4004000

Frames processed:                   5000 (0 - 4999)
FPS (min | max | average):          3.713 | 196079 | 49.20
Process memory usage (max):         739 MiB
Thread count:                       64
CPU usage (average):                8.5%

GPU usage (average):                98%
VPU usage (average):                0%
GPU memory usage:                   1128 MiB
GPU Power Consumption (average):    76.6 W

Time (elapsed):                     00:01:41.627
```

NNEDI3CL_enq.dll:
```
AVSMeter 3.0.9.0 (x64), (c) Groucho2004, 2012-2021
AviSynth+ 3.7.2 (r3679, master, x86_64) (3.7.2.0)

Number of frames:                     5000
Length (hh:mm:ss.ms):         00:01:23.417
Frame width:                          1288
Frame height:                          720
Framerate:                          59.940 (60000/1001)
Colorspace:                           YV24
Audio channels:                          2
Audio bits/sample:                      32 (Float)
Audio sample rate:                   48000
Audio samples:                     4004000

Frames processed:                   5000 (0 - 4999)
FPS (min | max | average):          8.900 | 227273 | 49.77
Process memory usage (max):         728 MiB
Thread count:                       64
CPU usage (average):                49.5%

GPU usage (average):                99%
VPU usage (average):                0%
GPU memory usage:                   1167 MiB
GPU Power Consumption (average):    77.1 W

Time (elapsed):                     00:01:40.472
```
NNEDI3CL_read performed ever so slightly worse consistently (by about ~1.1%, variance was low when repeating passes), but also used noticeably less CPU resources in doing so, those are about the only differences between all of them with `st=true`

**Comment by Asd-g** [comment] 2022-08-15 18:02
Thanks for the test.

The latest version 1.0.3 has parameter `st`.

**Closed as completed** 2022-08-20 07:33 UTC
